name: Build
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
      with:
        repository: aria2/aria2
        ref: release-1.37.0

    - run: sudo apt install -y gcc-mingw-w64-x86-64-win32 g++-mingw-w64-x86-64-win32 autopoint

    - run: curl -L https://github.com/imba-tjd/build-aria2/raw/master/configure.sh | bash

    - run: |
        make -j4
        x86_64-w64-mingw32-strip -s src/aria2c.exe

    - uses: actions/upload-artifact@main
      with:
        path: src/aria2c.exe
        name: aria2c
